---

- name: Register RHEL assets with subscription manager
  hosts: "{{ _hosts | default(omit)  }}"
  become: true

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - org_id is defined
          - activation_key is defined
          - org_id != ''
          - activation_key != ''
          - org_id != 'undef'
          - activation_key != 'undef'

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname | regex_replace('_', '-') }}"

    # Install subscription-manager if it's not there
    - name: Install subscription-manager
      ansible.builtin.dnf:
        name: subscription-manager
        state: present

    - name: Remove RHUI client packages
      ansible.builtin.dnf:
        name: rh-amazon-rhui-client*
        state: removed

    - name: Get current repos
      register: repos
      changed_when: false
      ansible.builtin.command:
        cmd: ls /etc/yum.repos.d/

    - name: Remove existing rhui repos
      loop: "{{ repos.stdout_lines }}"
      when: "'rhui' in item"
      ansible.builtin.file:
        path: "/etc/yum.repos.d/{{ item }}"
        state: absent

    - name: Install katello package
      when: sat_url is defined
      ansible.builtin.dnf:
        name: "https://{{ sat_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
        state: present
        validate_certs: false
        disable_gpg_check: true

    - name: Manage repos with subscription mangler
      ansible.builtin.lineinfile:
        path: /etc/rhsm/rhsm.conf
        regexp: '^manage_repos'
        line: 'manage_repos = 1'

    - name: Register subscription manager
      # community.general.redhat_subscription:
      #   state: present
      #   activationkey: "{{ activation_key }}"
      #   org_id: "{{ org_id }}"
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ activationKey }}"
        rhc_organization: "{{ organizationID }}"
      ansible.builtin.include_role:
        name: rhel-system-roles.rhc
